name: PowerShell

on:
  push:
    paths:
      - "**.ps1"
  pull_request:
    paths:
      - "**.ps1"
  workflow_dispatch:

jobs:
  powershell-check:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Analyze Scripts
        shell: pwsh
        run: |
          Import-Module PSScriptAnalyzer
          $results = Invoke-ScriptAnalyzer -Path . -Recurse
            if ($results.Count -gt 0) {
            $results | Format-Table
            exit 1
          }